### ISSUE TITLE
Unable to locate message source for category 'mailjet'.

### ISSUE THREAD

**Issue by SkermBE** [robuust/craft-mailjet#1]
When triggering Craft to send a test email i get the following error:

`Unable to locate message source for category 'mailjet'.`
<img width="1460" alt="Screenshot 2022-06-07 at 21 23 29" src="https://user-images.githubusercontent.com/104457513/172465179-23382caa-5dee-4814-899f-5bc9a0a75fb3.png">

Craft edition & version: Craft Solo 4.0.4
PHP version: 8.1.5
Database driver & version: MySQL 10.3.34
Mailjet Plugin Version: 1.0.1

**Comment by SkermBE** [comment]
@boboldehampsink any update on this?

**Comment by boboldehampsink** [comment]
Sorry for the late response. Are you using Craft in a non-default language? If so, does the error disappear if you use the default english language? Are you seeing the same error if you would install, say craftcms/mailgun (which this is just a slightly altered copy of).

**Comment by boboldehampsink** [comment]
Fixed in 1.0.2
